cargo-features = ["codegen-backend"]
[workspace]


resolver = "2"

members = [
    "assembler",
    "rusty_vm_lib",
    "vm",
    "oxide",
    "generate_archlib",
    "debugger",
]

[profile.dev]
codegen-backend = "cranelift"
