import { Button } from "std-widgets.slint";
import { Backend } from "backend.slint";


export component ActionButtons {

    property <length> button_padding: 10px;

    VerticalLayout {

        dump-core-btn := Button {
            width: self.min-width + button_padding;
            text: "Dump core";
            enabled: !Backend.running;
            clicked => {
                Backend.dump_core();
            }
        }
        view-debug-header-btn := Button {
            width: self.min-width + button_padding;
            text: "View debug header";
            clicked => {
                Backend.view_debug_header();
            }
        }
        advance-btn := Button {
            width: self.min-width + button_padding;
            text: "Step in";
            enabled: !Backend.running && !Backend.terminated;
            clicked => {
                Backend.step_in();
            }
        }
        continue-btn := Button {
            width: self.min-width + button_padding;
            text: "Continue";
            enabled: !Backend.running && !Backend.terminated;
            clicked => {
                Backend.continue();
            }
        }
        stop-btn := Button {
            width: self.min-width + button_padding;
            text: "Stop";
            enabled: Backend.running && !Backend.terminated;
            clicked => {
                Backend.stop();
            }
        }

    }


}
