import { Button } from "std-widgets.slint";


export component ActionButtons {

    property <length> button-padding: 10px;

    VerticalLayout {

        Button {
            width: self.min-width + button-padding;
            text: "Dump core";
        }
        Button {
            width: self.min-width + button-padding;
            text: "View debug header";
        }

        Button {
            width: self.min-width + button-padding;
            text: "Advance";
        }
        Button {
            width: self.min-width + button-padding;
            text: "Continue";
        }
        Button {
            width: self.min-width + button-padding;
            text: "Stop";
        }

    }


}
