import { ActionButtons } from "action_buttons.slint";
import { MemoryArea } from "memory.slint";
import { BreakpointArea } from "breakpoints.slint";
import { RegistersArea } from "registers.slint";
import { InstructionsArea } from "instructions.slint";
import { Styling } from "styling.slint";
// import { HorizontalSplitter } from "utils.slint";

export { Backend } from "backend.slint";


export component MainWindow inherits Window {

    in-out property <string> memory-view <=> memory-area.memory-view;
    in-out property <string> memory-lines <=> memory-area.memory-lines;
    in-out property <int> memory-start <=> memory-area.memory-start;
    in-out property <int> memory-span <=> memory-area.memory-span;


    VerticalLayout {

        spacing: Styling.inter-area-spacing;

        HorizontalLayout {

            height: 400px;
            spacing: Styling.inter-area-spacing;

            memory-area := MemoryArea {}
            BreakpointArea {}
            RegistersArea {}

        }


        HorizontalLayout {

            instructions-area := InstructionsArea {
                // width: splitter.x;
            }

            action-buttons := ActionButtons {
                // width: root.width - splitter.x;
            }
        }
    }

    // splitter := HorizontalSplitter {

    //     height: 100%;
    //     y: instructions-area.absolute-position.y;
    //     min-x: root.x + instructions-area.min-width;
    //     max-x: root.width - action-buttons.min-width;

    // }

}
