import { ListView, Button, CheckBox, StandardButton } from "std-widgets.slint";


export struct BreakPoint {
    name: string,
    location: string,
    enabled: bool,
}


component BreakpointLine {

    in-out property <BreakPoint> breakpoint;

    HorizontalLayout {

        alignment: space-between;

        Text {
            text: breakpoint.name;
        }
        Text {
            text: breakpoint.location;
        }

        HorizontalLayout {

            CheckBox {
                checked: breakpoint.enabled;
            }
            Button {
                width: self.min-width;
                text: "X";
            }
        }
    }

}

export component BreakpointArea {

    in-out property <[BreakPoint]> breakpoints;

    VerticalLayout {

        Text {
            text: "Breakpoints";
        }

        ListView {
            for bp in breakpoints : BreakpointLine {
                breakpoint: bp;
            }
        }

        HorizontalLayout {
            Button {
                text: "Add here";
            }
            Button {
                text: "Add at label";
            }
        }


    }

}
