import { TextEdit, ListView, ScrollView } from "std-widgets.slint";
import { SelectableText } from "utils.slint";

component InstructionLine inherits HorizontalLayout {

    in property <string> assembly;

    alignment: LayoutAlignment.start;

    SelectableText {
        text: assembly;
    }
}

export component InstructionsArea {

    VerticalLayout {
        Text {
            text: "Instructions";
        }
        ListView {



            for i in 6: InstructionLine {
                assembly: "mov r1 r2";
            }
        }
    }

}
