import { TextEdit, ListView, ScrollView } from "std-widgets.slint";
import { SelectableText } from "utils.slint";

component InstructionLine inherits HorizontalLayout {

    in property <string> assembly;

    alignment: LayoutAlignment.start;

    SelectableText {
        text: assembly;
    }
}

export component InstructionsArea {

    in-out property <[string]> instructions;

    callback scroll_to_bottom();
    scroll_to_bottom => {
        instructions_view.viewport-y = min(0px, - instructions_view.viewport-height + instructions_view.visible-height);
    }

    VerticalLayout {
        Text {
            text: "Instructions";
        }
        instructions_view := ListView {
            for instruction in instructions: InstructionLine {
                assembly: instruction;
            }
        }
    }

}
