import { ListView, Button, CheckBox, StandardButton } from "std-widgets.slint";

import { Backend } from "backend.slint";


export struct BreakPoint {
    name: string,
    location: string,
    replaced_value: int,
}


component BreakpointLine {

    in-out property <BreakPoint> breakpoint;

    HorizontalLayout {

        alignment: space-between;

        Text {
            text: breakpoint.name;
        }
        Text {
            text: breakpoint.location;
        }
        Text {
            text: "(" + breakpoint.replaced-value + ")";
        }

        Button {
            width: self.min-width;
            text: "X";
        }
    }

}

export component BreakpointArea {

    in-out property <[BreakPoint]> breakpoints;

    VerticalLayout {

        Text {
            text: "Breakpoints";
        }

        ListView {
            for bp in breakpoints : BreakpointLine {
                breakpoint: bp;
            }
        }

        HorizontalLayout {
            Button {
                enabled: !Backend.terminated;
                text: "Add here";
                clicked => {
                    Backend.add_breakpoint_here();
                }
            }
            Button {
                enabled: !Backend.terminated;
                text: "Add at label";
            }
        }


    }

}
