import { ListView, ScrollView, LineEdit } from "std-widgets.slint";

import { SelectableText } from "../utils.slint";

import { Backend } from "backend.slint";

global Shared {
    // Ordering matters
    out property <[string]> reg_names: ["r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "input", "error", "print", "int", "stp", "pc", "sbp", "zf", "sf", "rf", "cf", "of"];
}


component RegisterSetView {

    in property <[string]> registers;

    VerticalLayout {

        Rectangle {
            height: 2px;
            background: gray;
        }
        Rectangle {height: 5px;}

        for name[i] in Shared.reg_names : HorizontalLayout {
            alignment: start;
            Text {
                font-weight: 800;
                text: name;
            }
            Rectangle {width: 10px;}
            SelectableText {
                height: 2rem;
                text: registers[i];
            }
        }
    }
}

export component RegistersArea {

    in-out property <[[string]]> register_sets;

    callback scroll_to_bottom();
    scroll_to_bottom => {
        reg_view.viewport-y = min(0px, - reg_view.viewport-height + reg_view.visible-height);
    }

    VerticalLayout {
        Text {
            text: "Registers";
        }
        reg_view := ListView {
            for reg_set in register_sets: RegisterSetView {
                registers: reg_set;
            }
        }
    }

}
