import { HorizontalBox } from "std-widgets.slint";

import { SelectableText } from "../utils.slint";

import { Backend } from "backend.slint";

export component VMStatusArea inherits HorizontalLayout {

    alignment: start;

    HorizontalBox {
        Text {
            text: "Running:";
        }
        running_flag := Text {
            text: Backend.running ? "true" : "false";
        }
    }

    HorizontalBox {
        Text {
            text: "Terminated:";
        }
        terminated_flag := Text {
            text: Backend.terminated ? "true" : "false";
        }
    }

    HorizontalBox {
        Text {
            text: "Memory:";
        }
        tot_mem_text := SelectableText {
            text: Backend.total_memory;
        }
        Text {
            text: " Bytes";
        }
    }

}
