

# Generated Tue, 2 Jul 2024 21:07:16 +0000
# This is an automatically generated library file. Do not edit this file manually.
# This file contains enrivonment variables for the VM architecture. 


.text:

    %%- PRINT_SIGNED: 0
    %%- PRINT_UNSIGNED:1
    %%- PRINT_FLOAT: 2
    %%- PRINT_CHAR: 3
    %%- PRINT_STRING: 4
    %%- PRINT_BYTES: 5
    
    %%- INPUT_SIGNED: 6
    %%- INPUT_UNSIGNED: 7
    %%- INPUT_STRING: 8

    %%- RANDOM: 9

    %%- HOST_TIME_NANOS: 10
    %%- ELAPSED_TIME_NANOS: 11

    %%- DISK_READ: 12
    %%- DISK_WRITE: 13

    %%- TERM_INTR: 14

    %%- SET_TIMER_NANOS: 15

    %%- FLUSH_STDOUT: 16

    %%- HOST_FS_INTR: 17


    %%- NO_ERROR: 0
    %%- END_OF_FILE: 1
    %%- INVALID_INPUT: 2
    %%- ZERO_DIVISION: 3
    %%- STACK_OVERFLOW: 4
    %%- OUT_OF_BOUNDS: 5
    %%- UNALIGNED_ADDRESS: 6
    %%- PERMISSION_DENIED: 7
    %%- TIMED_OUT: 8
    %%- NOT_FOUND: 9
    %%- ALREADY_EXISTS: 10
    %%- INVALID_DATA: 11
    %%- INTERRUPTED: 12
    %%- OUT_OF_MEMORY: 13
    %%- WRITE_ZERO: 14
    %%- MODULE_UNAVAILABLE: 15

    %%- GENERIC_ERROR: 16

    