

# Generated Wed, 12 Jun 2024 10:16:42 +0000
# This is an automatically generated library file. Do not edit this file manually.
# This file contains enrivonment variables for the VM architecture. 


.text:

    %%- PRINT_SIGNED: 0
    %%- PRINT_UNSIGNED:1
    %%- PRINT_CHAR: 2
    %%- PRINT_STRING: 3
    %%- PRINT_BYTES: 4
    
    %%- INPUT_SIGNED: 5
    %%- INPUT_UNSIGNED: 6
    %%- INPUT_STRING: 7

    %%- RANDOM: 8

    %%- HOST_TIME_NANOS: 9
    %%- ELAPSED_TIME_NANOS: 10

    %%- DISK_READ: 11
    %%- DISK_WRITE: 12

    %%- TERM_INTR: 13

    %%- SET_TIMER_NANOS: 14

    %%- FLUSH_STDOUT: 15

    %%- HOST_FS_INTR: 16


    %%- NO_ERROR: 0
    %%- END_OF_FILE: 1
    %%- INVALID_INPUT: 2
    %%- ZERO_DIVISION: 3
    %%- STACK_OVERFLOW: 4
    %%- OUT_OF_BOUNDS: 5
    %%- UNALIGNED_ADDRESS: 6
    %%- PERMISSION_DENIED: 7
    %%- TIMED_OUT: 8
    %%- NOT_FOUND: 9
    %%- ALREADY_EXISTS: 10
    %%- INVALID_DATA: 11
    %%- INTERRUPTED: 12
    %%- OUT_OF_MEMORY: 13
    %%- WRITE_ZERO: 14
    %%- MODULE_UNAVAILABLE: 15

    %%- GENERIC_ERROR: 16

    