

# Generated Sun, 2 Feb 2025 09:57:28 +0000
# This is an automatically generated library file. Do not edit this file manually.
# This file contains enrivonment variables for the VM architecture.


.text:

    %%- PRINT_SIGNED: 0
    %%- PRINT_UNSIGNED:1
    %%- PRINT_FLOAT: 2
    %%- PRINT_CHAR: 3
    %%- PRINT_STRING: 4
    %%- PRINT_BYTES: 5

    %%- INPUT_SIGNED: 6
    %%- INPUT_UNSIGNED: 7
    %%- INPUT_BYTE: 8
    %%- INPUT_STRING: 9
    %%- STDIN_HAS_DATA: 10

    %%- RANDOM: 11

    %%- HOST_TIME_NANOS: 12
    %%- ELAPSED_TIME_NANOS: 13

    %%- DISK_READ: 14
    %%- DISK_WRITE: 15

    %%- TERM_INTR: 16

    %%- SET_TIMER_NANOS: 17

    %%- FLUSH_STDOUT: 18

    %%- HOST_FS_INTR: 19


    %%- NO_ERROR: 0
    %%- END_OF_FILE: 1
    %%- INVALID_INPUT: 2
    %%- ZERO_DIVISION: 3
    %%- STACK_OVERFLOW: 4
    %%- OUT_OF_BOUNDS: 5
    %%- UNALIGNED_ADDRESS: 6
    %%- PERMISSION_DENIED: 7
    %%- TIMED_OUT: 8
    %%- NOT_FOUND: 9
    %%- ALREADY_EXISTS: 10
    %%- INVALID_DATA: 11
    %%- INTERRUPTED: 12
    %%- OUT_OF_MEMORY: 13
    %%- WRITE_ZERO: 14
    %%- MODULE_UNAVAILABLE: 15

    %%- GENERIC_ERROR: 16

    