[package]
name = "debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
shared_memory = "0.12.4"
rusty_vm_lib = { path = "../rusty_vm_lib" }
slint = "1.9.2"

[build-dependencies]
slint-build = "1.9.2"
